Update nodejs-cd.yml
Added an exit 1 to the acceptance tests failed block

diff --git a/.github/workflows/nodejs-cd.yml b/.github/workflows/nodejs-cd.yml
--- a/.github/workflows/nodejs-cd.yml
+++ b/.github/workflows/nodejs-cd.yml
@@ -74,5 +74,7 @@ jobs:
 
     - name: Take Action On Acceptance Tests Failed
       if: steps.acceptance_tests.outcome != 'success'
-      run: echo "Acceptance Tests FAIL"
+      run: |
+        echo "Acceptance Tests FAIL"
+        exit 1
         
